/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bilginyilmaz;

import javax.imageio.plugins.bmp.BMPImageWriteParam;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class BilginYilmazDisplayGui extends javax.swing.JFrame {

    /**
     * Creates new form BilginYılmazDisplayGui
     */
    public BilginYilmazDisplayGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtn_pre = new javax.swing.JRadioButton();
        rbtn_ino = new javax.swing.JRadioButton();
        rbtn_post = new javax.swing.JRadioButton();
        btn_print = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_area_pre_in_post = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_search_area = new javax.swing.JTextArea();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        btn_group.add(rbtn_pre);
        rbtn_pre.setText("PreOrder");

        btn_group.add(rbtn_ino);
        rbtn_ino.setText("InOrder");

        btn_group.add(rbtn_post);
        rbtn_post.setText("PostOrder");

        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        txt_area_pre_in_post.setColumns(20);
        txt_area_pre_in_post.setRows(5);
        jScrollPane2.setViewportView(txt_area_pre_in_post);

        txt_search_area.setColumns(20);
        txt_search_area.setRows(5);
        jScrollPane3.setViewportView(txt_search_area);

        btn_back.setText("Go Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btn_print)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtn_pre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(rbtn_ino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbtn_post, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_back))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(btn_search)))
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_pre)
                    .addComponent(rbtn_ino)
                    .addComponent(rbtn_post)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btn_print))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_back)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void preOrder(BilginYilmazBNode node) {
        int sum = 0;
        if (node != null && node.file_list != null) {
            BilginYilmazFNode fnode = node.file_list.head;
            while (fnode != null) {
                sum += fnode.data;
                fnode = fnode.next;
            }
        }
        if (node != null) {
            txt_area_pre_in_post.append(node.data + "," + sum + "\n");
            node.printFileList();
            preOrder(node.left);
            preOrder(node.right);
        }

    }

    public void inOrder(BilginYilmazBNode node) {
        
        int sum = 0;
        if (node != null && node.file_list != null) {
            BilginYilmazFNode fnode = node.file_list.head;
            while (fnode != null) {
                sum += fnode.data;
                fnode = fnode.next;
            }
        }
        if (node != null) {
            inOrder(node.left);
            txt_area_pre_in_post.append(node.data + "," + sum + "\n");
            node.printFileList();
            inOrder(node.right);
        }
    }

    public void postOrder(BilginYilmazBNode node) {
        int sum = 0;
        if (node != null && node.file_list != null) {
            BilginYilmazFNode fnode = node.file_list.head;
            while (fnode != null) {
                
                sum += fnode.data;
                fnode = fnode.next;
            }
        }
        if (node != null) {
            postOrder(node.left);
            postOrder(node.right);
            txt_area_pre_in_post.append(node.data + "," + sum + "\n");
            node.printFileList();
        }
    }
    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        txt_area_pre_in_post.setText("");
        if (rbtn_pre.isSelected()) {
            txt_area_pre_in_post.append("PRE ORDER:\n");
            preOrder(BilginYilmazTreeGui.BTree.root);

        }
        if (rbtn_post.isSelected()) {
            txt_area_pre_in_post.append("POST ORDER:\n");
            postOrder(BilginYilmazTreeGui.BTree.root);

        }
        if (rbtn_ino.isSelected()) {
            txt_area_pre_in_post.append("IN ORDER:\n");
            inOrder(BilginYilmazTreeGui.BTree.root);

        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        try{
        String word=txt_search.getText().toLowerCase();
        
        BilginYilmazBNode newn=BilginYilmazTreeGui.BTree.root;
         while (true) {
             
                if(newn.data.compareTo(word)==0){
                    
                    txt_search_area.setText(word);
                    BilginYilmazFNode fnode=newn.file_list.head;
                    int sum=0;
                while(fnode!=null){
                sum+=fnode.data;
                txt_search_area.append(" "+fnode.file_name+",");
                fnode=fnode.next;
                }
                txt_search_area.append(sum+"\n");
                break;
                }
                else if(newn.data.compareTo(word)<0){
                newn=newn.right;
                }
                else if(newn.data.compareTo(word)>0){
                newn=newn.left;
                }
            }}
        catch(Exception E){
            JOptionPane.showMessageDialog(null, "Word doesn't exist!");
        }
        
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        BilginYilmazTreeGui b=new BilginYilmazTreeGui();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BilginYilmazDisplayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BilginYilmazDisplayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BilginYilmazDisplayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BilginYilmazDisplayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BilginYilmazDisplayGui().setVisible(true);
//            }
//        })
//    ;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.ButtonGroup btn_group;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_search;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbtn_ino;
    private javax.swing.JRadioButton rbtn_post;
    private javax.swing.JRadioButton rbtn_pre;
    private javax.swing.JTextArea txt_area_pre_in_post;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextArea txt_search_area;
    // End of variables declaration//GEN-END:variables
}
